mainmatter/ember-promise-modals

.travis.yml, README.md, package.json
because the Node team is no longer maintaining it either...
=> Drop Support for Node.js 8

package.json
`ember-cli-htmlbars` takes care of this now
=> Remove obsolete `ember-cli-htmlbars-inline-precompile` dependency

README.md, package.json
That way it's easier to support multiple versions of `ember-animated` in parallel, since the host app version will automatically be used, without causing issues with `ember-cli-dependency-lint`.
=> Convert `ember-animated` to a peer dependency

addon/components/modal.js
There is no such thing as `willRemoveElement()`, I probably meant `willDestroyElement()`  😅 
This should unblock #178
=> components/modal: Fix broken destructor

package.json, yarn.lock
This makes it significantly easier to debug things using `console.log()` 😉
=> Add `qunit-console-grouper` dev dependency

addon/services/modals.js
When running the test suite and a test is not closing the modal at the end then the `.epm-scrolling-disabled` CSS class will not be reset properly. This PR fixes the issue by ensuring that the class is always removed in the destructor.
=> service/modals: Reset `.epm-scrolling-disabled` class in the destructor

addon/components/modal.js, addon/services/modals.js, tests/application/basics-test.js
This can be used to deactivate the click-outside-closes-modal behavior that is currently enabled by default
=> Expose `clickOutsideDeactivates` on the `modals` service

.eslintrc.js, package.json, yarn.lock
We still used the default eslint parser whereas more modern ember uses babel-eslint which supports decorators etc.
=> use babel-eslint as eslint parser

addon/modal.js, addon/services/modals.js, config/ember-try.js, tests/unit/services/modals-test.js
We had a small regression where the backdrop would only start animating out until after the last modal was done animating out itself. This is not the wanted/expected behavior. It should start it's animation at the same time as the modal.
=> fix backdrop not animating immediately after the last modal is closed

addon/styles/ember-promise-modals.css
Browsers seem to have some bug where CSS variables are not always cascaded correctly when using an animation shorthand. Specifying these properties separately makes sure they're actually being applied as expected.
=> explicitly specify animation delay and duration as separate to make sure they're properly used by the browser

README.md, addon/modal.js, tests/unit/services/modals-test.js
This hook is called when the modal finishes its closing animation. Can be used to for example clean up CSS variable overrides.
=> add optional onAnimationModalOutEnd hook

.github/workflows/deploy.yml
This should allow us to see the demos directly on GitHub. I do get that we use Netlify for the PR previews, but I think it's sensible to keep the main demo on the same platform as the code and GitHub pages make that rather easy.
=> Deploy dummy application to Github pages

tests/dummy/config/environment.js
The GitHub page is in a subfolder and the `index.html` targets root otherwise.
=> Update production build path for GitHub pages

package.json
Otherwise the dummy shows up empty on GitHub pages.
=> Use env=production when building the dummy application

tests/dummy/app/styles/app.css
We were enforcing `width`s on the modals while they should have been `max-width` to stay responsive.
=> Fix responsiveness of dummy app

package.json, tests/dummy/config/optional-features.json
This was throwing in CI. Apparently it's required now. Generated through `npx @ember/octanify`
=> Specify octane edition in package.json & add missing optional features

README.md, addon/components/modal.js, addon/services/modals.js, tests/integration/configuration/focus-trap-test.js
=> Add option to disable focus trap

README.md, addon/modal.js, addon/services/modals.js, config/ember-try.js
This should allow us to support Ember versions down to Ember 2.18, providing a good path forward for very old apps as a final change to the 2.0 release cycle of this addon.
=> Legacy: Downgrade native class to Ember.Object

README.md, addon/components/modal.js, addon/services/modals.js, tests/application/basics-test.js, tests/integration/configuration/focus-trap-test.js
- Support focus trap options on a per-modal basis
- Move `clickOutsideDeactivates` along with the rest of focus trap options
- Replace `disableFocusTrap` with `focusTrapOptions = null`
=> Enhance focus trap configuration

addon/components/modal.js, tests/application/basics-test.js, tests/dummy/app/controllers/application.js, tests/dummy/app/templates/components/modal1.hbs
This wasn't covered by our test suite before.
Expected behavior: Calling `@close` on a modal will close the modal and in turn should resolve the modal promise with any arguments passed to that function. 
Actual behavior: Closing the modal also triggers `focus-out`, which in turn also calls the modal close callback but without any return data, racing the manual call to `@close`, which means the modal promise is resolved with `undefined` because the `onDeactivate` hook of `focus-out` runs before the modal close.
This happens because `focus-out` changed when it's `onDeactivate` hook is triggered, introducing a new `onPostDeactivate` which has the same timing as the old one.
=> Ensure calls to @close run before the focus-out deactivation

addon/components/modal.js
Turns out `focus-trap` was not the culprit here, but the fact that we resolved the modal _after_ calling the `deactivate` method on the focus trap.
The changes to the events in the dependency were purely coincidental, but using the newly introduced events happended to fix the issue as well as the `onPostDeactivate` happens to run a tick later than the `onDeactivate` which is enough for the `resolve` to happen.
Re #565
=> Refactor handling of `focusTrap.onDeactivate` method

addon/components/modal.js
This is start of a chain of refactorings with the goal to make the modal component and it's various states more comprehensible and easier to change. 
While it _should_ not be an issue, it _may_ happen that a reference to the DOM element that represents the modal gets stuck in memory. Retrieving the element from DOM each time seems to make the garbage collector happier. 
This method could and should be replaced by a regular getter once we shift this addon to native classes.
=> Replace retained element reference with a method

addon/components/modal.js, addon/services/modals.js, addon/templates/components/modal.hbs, package.json, pnpm-lock.yaml, tests/integration/components/modal-test.js
To be rebased & merged after #684
Extracting the way we control the event that closes the modal after the animation stops. This also renames the properties and methods that handle the `animationend` event to be more generic as future features #637 would be very confusing otherwise.
=> Move attaching/detaching `animationend` event handler into methods and generalize related names

addon/components/modal.js, tests/application/basics-test.js
To be rebased & merged after #685
Before this change `epm-animating` class won't be set when _closing_ the modal, possibly making the outgoing animations potentially sluggish or wobbly.
=> Closing the modal should inform the modals service

addon/components/modal.js, addon/modal.js, addon/services/modals.js
The "private" `_destroy()` method is used when the service instance is destroyed and also in the test helper to tear down any remaining modals between tests.
=> Extract destruction of the modals effects into a method and apply them

addon/modal.js
Mostly personal preference, but potentially easier to understand. Less indentation is always a welcome bonus. 
It doesn't change behavior, but I spotted this and didn't want to foist it into one of the other PRs.
=> Prefer "happy path" code style for `_resolve()`

config/ember-try.js
The configuration held some outdated information on ember-auto-import v2 which was moved to requirements for this addon a few months ago.
=> Update ember-try configuration

tests/dummy/config/environment.js
Namespace only required if we're visiting GH pages directly, it should be / for custom domains
=> Set production rootURL to /

addon-test-support/index.js, tests/application/destroy-test.js
Currently the `setupPromiseModals` test helper doesn't wait for the modal destruction test waiter to settle.
This might cause a race condition with other registered destructors.
By waiting for the application to settle after our modals are destroyed we are making sure the next queued destructor operates on a "clean slate"
=> setupPromiseModals should wait for test waiters to settle

tests/dummy/app/index.html
Plausible is cookie-free so no cookie banner necessary.
=> Enable analytics via Plausible

DEPRECATIONS.md, README.md, addon/modal.js, addon/services/modals.js, addon/templates/components/modal.hbs, config/ember-try.js, ember-cli-build.js, package.json, pnpm-lock.yaml, tests/application/deprecations-test.js, tests/dummy/config/environment.js
This is step 1 to convert ember-promise-modals to a v2 addon. 
In Embroider, it will no longer be possible to pass components by string, as explained in the [Replacing Component Helper](https://github.com/embroider-build/embroider/blob/main/docs/replacing-component-helper.md) guide. Only passing a class will be allowed.
This PR deprecates the possibility of passing a component as string to the modal:
- it implements and tests the deprecation
- it deactivates the new test for embroider-optimized scenario because passing by string will no longer work at all in Embroider
=> Deprecate modal from string

DEPRECATIONS.md, README.md, addon/services/modals.js
PR #894 introduces the `DEPRECATIONS.md` file that contains a section about `ember-promise-modals.modals-from-string`, to prepare the addon to Embroider ecosystem.
This PR adds additional sections about more general things that will be dropped in the v2 addon:
- Ember < 3.28
- node < 16 (due to more recent dependencies that require node 16)
- The PostCSS process.
=> Docs/ Communicate about all the major changes planned for the v2 addon

package.json
PR #858 removed node 14 from the list of supported engines after struggling with CI failures. It turns out the issues are now fixed and the CI is green when run with node 14 (this was tested in #906, and the CI was ✅).
=> Fix(node support)/ Re-add node 14 to the list of supported engines

DEPRECATIONS.md
Following the re-adding of node 14 (#907), adjust the line about the deprecated node versions.
=> docs(DEPRECATIONS)/ Adjust the line about deprecated node

DEPRECATIONS.md, MIGRATION.md, README.md, index.js, package.json, pnpm-lock.yaml
This PR is a step of the conversion to v2 addon.
- It removes the PostCSS process entirely to ease future conversion. 
- It reworks the related docs to turn the deprecation into a migration guide.
**Why?**
Build-time features no longer stand in Embroider world, because the v2 addons are static. To provide a processed CSS, we need to provide it statically, and this is not what we want: this process generated static fallbacks for CSS variables, but most browsers have been supporting CSS variables for several years. Also, the v1 addon offered the possibility to import the uncompiled style, so providing processed styles would kind of break this. The approach we chose is to remove this feature from the addon completely and document how to re-implement it on consumer app side.
=> Remove the PostCSS process

.github/workflows/ci.yml, .github/workflows/release.yml, DEPRECATIONS.md, README.md, config/ember-try.js, package.json, tests/dummy/config/optional-features.json
This PR is a step of the conversion to v2 addon.
- It removes the support for Ember < 3.28
- It removes support for node < 16
**Why?**
Once the addon is converted to v2, the ember-try scenario start failing for Ember < 3.28. Also, the addon will require dependencies like `ember-cli-babel@8.2.0` (to support static blocks) that require at least node 16.
Additionally, the PR: 
- resets the `jquery-integration` to `false`.
- downgrade a node version to 16 in the CI to make sure 16 is still supported.
=> Drop Ember < 3.28 and node < 16

.eslintrc.js, package.json, pnpm-lock.yaml
`eslint-plugin-n` is initially a fork of `eslint-plugin-node` as the latter seemed no longer maintained. 
Moving to `eslint-plugin-n >= 15.4.0` is important for the conversion to v2 addon, because this version includes a patch that prevents `no-unpublished-required` from reporting errors when `devDependencies` are imported in private packages. This is a common lint error that shows up when restructuring v1 addons to monorepos for the conversion.
=> Replace eslint-plugin-node with latest eslint-plugin-n

.github/workflows/deploy.yml
PR #916 introduced `pnpm` command in the `deploy.yml` flow, but pnpm package manager has not been installed in the workflow. This PR adds the missing install using the exact same commands as the `ci.yml` workflow.
=> Fix deploy flow

.github/workflows/deploy.yml
The build addon step was missing from the deploy workflow of the test app.
=> CI (fix): Build the addon before building and deploying the test app

.github/workflows/deploy.yml
The #924 fix was done a bit in a rush. Adding the missing addon build is a thing, but we also need to install the dependencies before we can build the addon. Here the `pnpm install` was part of the "Install and Build" test-app instructions below.
=> ci (fix): in the deploy workflow, move the install before the addon build

package.json, packages/test-app/package.json
This repository is a mono-repo that contains a top-level `package.json` and two packages. The top-level package and the test-app package are `private` and are not meant to be published to `npm`. Therefore, `release-plan`, the tool we use to automate the release, doesn't update their number version (which is fundamentally useless). 
This PR removes the `version` field for `private` packages.
=> Remove version numbers on private packages
